name: Deploy Backend

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch: # Bisa trigger manual

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set branch variable
        run: |
          if [ -n "${GITHUB_HEAD_REF}" ]; then
            echo "BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          else
            echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "Deploying branch: $BRANCH"

            if [ "$BRANCH" == "main" ]; then
              APP_DIR="${{ secrets.APP_DIR_PROD }}"
              PM2_NAME="verba-backend"
            elif [ "$BRANCH" == "staging" ]; then
              APP_DIR="${{ secrets.APP_DIR_STAGING }}"
              PM2_NAME="verba-backend-staging"
            else
              echo "Branch $BRANCH tidak deploy. Doing nothing."
              exit 0
            fi

            cd $APP_DIR

            # Pastikan Git user di-set
            git config --global user.name "Hizrawan"
            git config --global user.email "hizrawandwioka@gmail.com"

            # Sinkronisasi branch dengan remote
            git fetch origin
            git reset --hard origin/$BRANCH

            # Install dependencies dan restart PM2
            npm install
            pm2 restart $PM2_NAME

            # Test dan reload NGINX
            sudo nginx -t
            sudo systemctl reload nginx
