name: Deploy Staging Backend

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Staging EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "==== DEPLOY PRODUCTION START ===="

            APP_DIR="${{ secrets.APP_DIR_STAGING }}"
            PM2_NAME="verba-backend-staging"
            NODE_ENV="staging"
            PORT=3000

            echo "Deploying $PM2_NAME ($NODE_ENV) in $APP_DIR"

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            cd $APP_DIR || exit 1

            if [ ! -d "$APP_DIR/.git" ]; then
              git clone --branch staging https://github.com/Hizrawan/verba-backend.git $APP_DIR
            fi

            cd $APP_DIR
            git fetch origin
            git reset --hard origin/staging

            npm install

            export NODE_ENV=$NODE_ENV
            export PORT=$PORT

            pm2 restart $PM2_NAME 

            sudo nginx -t
            sudo systemctl reload nginx

            echo "âœ… Staging deploy completed"
            echo "==== DEPLOY PRODUCTION END ===="
